language: python
python:
 - "3.6"

before_install: sudo apt-get update

install:
 - sudo apt-get install python3-pip
 - pip install tox-travis
 - pip install -r requirements.txt

script:
 - flask run &
 - tox

